---
observations: kmer_counts_rle.bed
mode: nb

observation_rate:
  output_file: obs_rate.bed
  bin_size: 1000000

train:
  start_params: None
  output_file: trained.json

decode:
  use_viterbi: True
  output_path_file: path.txt
  output_tracts_file: tracts.txt